#!/bin/sh

LIBTOOLIZE="libtoolize"

if [ "x`which $LIBTOOLIZE`" = "x" ]; then
    LIBTOOLIZE="glibtoolize"
fi

if [ "x`which $LIBTOOLIZE`" = "x" ]; then
    echo "Neither libtoolize nor glibtoolize could be found!"
    exit 1
fi

${LIBTOOLIZE} --copy --automake --force
${ACLOCAL:-aclocal} -I m4 $ACLOCAL_FLAGS
${AUTOHEADER:-autoheader}
${AUTOCONF:-autoconf}
${AUTOMAKE:-automake} --add-missing --copy
