.TH spindly_template 3 "9 Jul 2012" "spindly 0.1" "spindly manual"
.SH NAME
spindly_template - short function description
.SH SYNOPSIS
.nf
#include <spindly.h>

void spindly_template(void);
.fi
.SH DESCRIPTION
Long text describing the function and its input arguments.
.SH RETURN VALUE
Describe what the function returns.
.SH ERRORS
Add error codes
.SH SEE ALSO
Add related functions
