#ifndef SPDY_ERROR_H_
#define SPDY_ERROR_H_ 1

#include <spindly.h>

/* this used to be the "enum SPDY_ERRORS" */

#define SPDY_ERROR_NONE SPINDLYE_OK
#define SPDY_ERROR_MALLOC_FAILED SPINDLYE_NOMEM
#define SPDY_ERROR_INVALID_DATA SPINDLYE_INVAL
#define SPDY_ERROR_INSUFFICIENT_DATA SPINDLYE_INSUFF
#define SPDY_ERROR_ZLIB_DEFLATE_FAILED SPINDLYE_ZLIB
#define SPDY_ERROR_ZLIB_INFLATE_FAILED SPINDLYE_ZLIB
#define SPDY_ERROR_ZLIB_DEFLATE_INIT_FAILED SPINDLYE_ZLIB
#define SPDY_ERROR_ZLIB_INFLATE_INIT_FAILED SPINDLYE_ZLIB
#define SPDY_ERROR_ZLIB_DEFLATE_DICT_FAILED SPINDLYE_ZLIB
#define SPDY_ERROR_ZLIB_INFLATE_DICT_FAILED SPINDLYE_ZLIB
#define SPDY_ERROR_STREAM_RST SPINDLYE_RESET
#define SPDY_ERROR_STREAM_FIN SPINDLYE_STOP
#define SPDY_ERROR_TOO_SMALL_BUFFER SPINDLYE_SMALL_BUFFER

#endif
